name: latlng
description: GeoJSON, Geodesy and Geographical calculations for Dart. Provides LatLong and Mercator projection (EPSG4326).
version: 2.0.1
repository: https://github.com/xclud/dart_latlng
homepage: https://pwa.ir

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
