name: latlng
description: GeoJSON, Geodesy and Geographical calculations for Dart. Provides LatLong and Mercator projection (EPSG4326).
version: 1.0.0
repository: https://github.com/xclud/dart_latlng
homepage: https://pwa.ir

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.21.3
  lints: ^2.0.0
